[package]
name = "sci_rust"
version = "0.0.2"
edition = "2021"
description = "A scientific Rust library."
license = "MIT"
repository = "https://github.com/AlmostAnEngineer/sci_rust.git"

[dependencies]
num = "0.4.3"
rand = "0.8.0"
num-traits = "0.2.19"
